# 서버 포트 설정
server:
  port: 9000
  servlet:
    encoding:
      force: true
      charset: UTF-8
# database 연동 설정
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring2?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_ROOT_PASSWORD}
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update


  # gpt
chatgpt:
  api-key: ${API-KEY}